services:
  - type: web
    name: crystal-grimoire-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python unified_backend.py"
    plan: free
    healthCheckPath: "/health"
    envVars:
      - key: PORT
        value: 7888
      - key: HOST
        value: "0.0.0.0"