name: Deploy Crystal Grimoire to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.x'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build web app
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
      run: flutter build web --release --base-href="/CrystalGrimoire-Production/" --dart-define=GEMINI_API_KEY=$GEMINI_API_KEY --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY --dart-define=STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        cname: crystalgrimoire.domusgpt.com